vowels = set('aeiuo')
word = input("Provide a word to search for vowels:  ")
u = vowels.union(set(word))
print(u)
u_list = list(sorted(vowels))
print(u_list)
d = vowels.difference(set(word))
print(d)
i = vowels.intersection(word)
print(i)